name: QA

on:
    push:
        branches: [ "main", "development" ]
    pull_request:
        branches: [ "main", "development" ]

jobs:
    laravel-tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                include:
                    -   laravel: "^11.0"
                        testbench: "^9.0"

                    -   laravel: "^12.0"
                        testbench: "^10.0"

                    -   laravel: "^13.0"
                        testbench: "^11.0"

        steps:
            -   uses: actions/checkout@v3
                with:
                    submodules: true

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "8.3"

            -   name: Install dependencies
                run: |
                    composer require \
                      "laravel/framework:${{ matrix.laravel }}" \
                      "orchestra/testbench:${{ matrix.testbench }}" \
                      --no-interaction --no-update
                    
                    composer update --prefer-dist --no-interaction

            -   name: Run tests
                run: vendor/bin/phpunit